#!/usr/bin/env python3
"""Regenerate the decomp-derived half of the voice cast table.

Actor overlays assign their own text ids in the decompiled source, so which
character speaks a line is recorded there and can be recovered without playing
the game. Writes VoiceCastGenerated.h; run it after pulling new decomp work.

A text id claimed by more than one actor is dropped rather than guessed, and so
is anything below 0x1000: those bands are system, item-get and sign text that no
character speaks, so an actor owning one is the actor that puts the box on screen
rather than the one talking. Both rules exist because a wrong voice is worse than
no voice.
"""

import collections
import glob
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
OUT = HERE / "soh/soh/Enhancements/tts/VoiceCastGenerated.h"
LITERAL = r"(0x[0-9A-Fa-f]{2,4})"
CALLS = [re.compile(p) for p in (
    r"textId\s*=\s*" + LITERAL,
    r"Message_StartTextbox\s*\(\s*(?:play|globalCtx)\s*,\s*" + LITERAL,
    r"Message_ContinueTextbox\s*\(\s*(?:play|globalCtx)\s*,\s*" + LITERAL,
)]
# One character gets one voice, but the game splits several of them across
# overlays. Child and adult stay apart: they are cast separately on purpose.
ALIASES = {
    "En_Zl1": "zelda_child", "En_Zl4": "zelda_child",
    "En_Zl2": "zelda", "En_Zl3": "zelda",
    "En_Xc": "sheik",
    "En_Sa": "saria",
    "En_Elf": "navi",
    "En_Ma1": "malon_child", "En_Ma2": "malon", "En_Ma3": "malon",
    "En_Ru1": "ruto_child", "En_Ru2": "ruto",
    "En_Heishi1": "guard", "En_Heishi2": "guard",
    "En_Heishi3": "guard", "En_Heishi4": "guard",
    "En_Go": "goron", "En_Go2": "goron",
    "En_Du": "darunia",
    "En_Nb": "nabooru",
    "En_In": "ingo",
    "En_Ta": "talon",
    "En_Owl": "owl",
    "En_Ossan": "shopkeeper",
    "En_Daiku": "carpenter", "En_Daiku_Kakariko": "carpenter",
    "En_Niw_Lady": "cucco_lady",
}

TABLE = re.compile(r"(?:[Tt]ext[Ii]d|[Mm]essage|[Mm]sg)\w*\s*\[\s*\w*\s*\]\s*=\s*\{([^}]*)\}", re.S)


def scan():
    by_actor = collections.defaultdict(set)
    for path in sorted(glob.glob(str(HERE / "soh/src/overlays/actors/ovl_*/*.c"))):
        actor = Path(path).parent.name[4:]
        source = Path(path).read_text(encoding="utf-8", errors="replace")
        for pattern in CALLS:
            for match in pattern.finditer(source):
                by_actor[actor].add(int(match.group(1), 16))
        for match in TABLE.finditer(source):
            for hexlit in re.findall(LITERAL, match.group(1)):
                by_actor[actor].add(int(hexlit, 16))
    return by_actor


def main():
    by_actor = scan()
    claims = collections.defaultdict(set)
    for actor, ids in by_actor.items():
        for textid in ids:
            claims[textid].add(actor)

    FIRST_SPOKEN_ID = 0x1000
    rows = sorted((t, next(iter(a))) for t, a in claims.items()
                  if len(a) == 1 and t >= FIRST_SPOKEN_ID)
    dropped = sum(1 for a in claims.values() if len(a) > 1)
    unspoken = sum(1 for t, a in claims.items() if len(a) == 1 and t < FIRST_SPOKEN_ID)

    lines = [
        "// Generated by scripts/voice-cast-from-decomp.py - do not edit.",
        "// Text ids whose speaking actor is named in the decompiled source.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace SOH {",
        "",
        "struct GeneratedCastEntry {",
        "    uint16_t textId;",
        "    const char* profile;",
        "};",
        "",
        f"// {len(rows)} text ids from {len(by_actor)} actors. {dropped} claimed by more",
        f"// than one actor and {unspoken} below 0x1000 were dropped rather than guessed.",
        f"inline constexpr GeneratedCastEntry kGeneratedCast[{len(rows)}] = {{",
    ]
    lines += ['    { 0x%04X, "%s" },' % (t, ALIASES.get(a, a.lower())) for t, a in rows]
    lines += ["};", "", "} // namespace SOH", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{OUT.relative_to(HERE)}: {len(rows)} entries, {len(by_actor)} actors, "
          f"{dropped} ambiguous and {unspoken} unspoken-band dropped")


if __name__ == "__main__":
    sys.exit(main())
